#!/bin/bash

RESOLUTIONS=$(xrandr | grep -w "connected" | sed 's/primary//g'| awk '{print $3}')

FILE=$(readlink -f $1)

if [ ! -f "$FILE" ]; then
    echo "file: $FILE doesn't exist"
    exit 1
fi

echo $FILE > $HOME/.currentwallpaper

killall -q xwinwrap

pgrep -x xwinwrap || echo "$RESOLUTIONS" | while read line ; do 
xwinwrap -ov -g $line -- mpv -wid WID $FILE --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings &
done
